@startuml
node routes
node config
node autoload
node controller
node helper
node model

routes --> config
autoload <- config
routes ---> controller
config <-- controller
controller -> helper
config <- helper
routes --> helper
model <- controller
model --> config
@enduml